# Change these first
owner: germanoddo # Your GitHub organization or username, where this repository lives
repo: webstatus # The name of this repository

sites:
  - name: Prex-Argentina
    url: https://www.prexcard.com.ar
    icon: https://www.banderas-mundo.es/data/flags/h80/ar.png
    #icon: https://www.prexcard.com.ar/assets/img/2020/favicon/favicon-32.png
  - name: Prex-Chile
    url: https://prexcard.cl/
    icon: https://www.banderas-mundo.es/data/flags/h80/cl.png
    #icon: https://pub-app-s3-prexpe.s3.sa-east-1.amazonaws.com/web_assets/img/favicon/favicon-32.png
  - name: Prex-Perú
    url: https://www.prex.com.pe
    icon: https://www.banderas-mundo.es/data/flags/h80/pe.png
    #icon: https://pub-app-s3-prexpe.s3.sa-east-1.amazonaws.com/web_assets/img/favicon/favicon-32.png
  - name: Prex-Uruguay
    url: https://www.prexcard.com
    icon: https://www.banderas-mundo.es/data/flags/h80/uy.png
    #icon: https://de2aqb3kqoyo2.cloudfront.net/public/includes/assets/favicon.ico



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: webstatus.prexcard.com
  #demo.upptime.js.org
  baseUrl: /webstatus
  logoUrl: https://prexcard.s3.us-east-1.amazonaws.com/web/newassets/prexnew.png
  name: WebStatus
  #introTitle: "**WebStatus - Prex**"
  introMessage: Información actualizada sobre la disponibilidad de los servicios de Prex.
  navbar:
    - title: Status
      href: /
    #- title: GitHub
     #href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
