# Change these first
owner: germanoddo # Your GitHub organization or username, where this repository lives
repo: webstatus # The name of this repository

sites:
  - name: Prex-Argentina
    url: https://www.prexcard.com.ar
    icon: https://www.prexcard.com.ar/favicon.ico
  - name: Prex-Perú
    url: https://www.prexcard.com.ar
  - name: Prex-Uruguay
    url: https://www.prexcard.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: webstatus.prexcard.com
  #demo.upptime.js.org
  #baseUrl: /webstatus
  logoUrl: https://prexcard.s3.us-east-1.amazonaws.com/web/newassets/prexnew.png
  name: WebStatus
  #introTitle: "**WebStatus - Prex**"
  introMessage: Información actualizada sobre la disponibilidad de los servicios de Prex. Vuelve aquí en cualquier momento para obtener información sobre el estado actual.
  navbar:
    - title: Status
      href: /
    #- title: GitHub
     #href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
